# Generated by Django 5.1 on 2024-08-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_details',
            fields=[
                ('reg_no', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('percentage', models.FloatField()),
                ('cpourse', models.CharField(max_length=100)),
                ('fee', models.FloatField()),
            ],
        ),
    ]
