# Generated by Django 5.1 on 2024-08-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
