# Generated by Django 5.1 on 2024-08-09 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_details_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_details',
            old_name='cpourse',
            new_name='course',
        ),
    ]
